services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadam-backend           # ok de garder ce nom d’affichage
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - cadamnet

  nginx:
    image: nginx:alpine
    container_name: cadam-nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - cadamnet

networks:
  cadamnet:
    driver: bridge
